export const COUNTRY_CODES = [
  { flag: '🇵🇭', dial: '+63',   name: 'Philippines' },
  { flag: '🇦🇫', dial: '+93',   name: 'Afghanistan' },
  { flag: '🇦🇱', dial: '+355',  name: 'Albania' },
  { flag: '🇩🇿', dial: '+213',  name: 'Algeria' },
  { flag: '🇦🇩', dial: '+376',  name: 'Andorra' },
  { flag: '🇦🇴', dial: '+244',  name: 'Angola' },
  { flag: '🇦🇬', dial: '+1268', name: 'Antigua and Barbuda' },
  { flag: '🇦🇷', dial: '+54',   name: 'Argentina' },
  { flag: '🇦🇲', dial: '+374',  name: 'Armenia' },
  { flag: '🇦🇺', dial: '+61',   name: 'Australia' },
  { flag: '🇦🇹', dial: '+43',   name: 'Austria' },
  { flag: '🇦🇿', dial: '+994',  name: 'Azerbaijan' },
  { flag: '🇧🇸', dial: '+1242', name: 'Bahamas' },
  { flag: '🇧🇭', dial: '+973',  name: 'Bahrain' },
  { flag: '🇧🇩', dial: '+880',  name: 'Bangladesh' },
  { flag: '🇧🇧', dial: '+1246', name: 'Barbados' },
  { flag: '🇧🇾', dial: '+375',  name: 'Belarus' },
  { flag: '🇧🇪', dial: '+32',   name: 'Belgium' },
  { flag: '🇧🇿', dial: '+501',  name: 'Belize' },
  { flag: '🇧🇯', dial: '+229',  name: 'Benin' },
  { flag: '🇧🇹', dial: '+975',  name: 'Bhutan' },
  { flag: '🇧🇴', dial: '+591',  name: 'Bolivia' },
  { flag: '🇧🇦', dial: '+387',  name: 'Bosnia and Herzegovina' },
  { flag: '🇧🇼', dial: '+267',  name: 'Botswana' },
  { flag: '🇧🇷', dial: '+55',   name: 'Brazil' },
  { flag: '🇧🇳', dial: '+673',  name: 'Brunei' },
  { flag: '🇧🇬', dial: '+359',  name: 'Bulgaria' },
  { flag: '🇧🇫', dial: '+226',  name: 'Burkina Faso' },
  { flag: '🇧🇮', dial: '+257',  name: 'Burundi' },
  { flag: '🇰🇭', dial: '+855',  name: 'Cambodia' },
  { flag: '🇨🇲', dial: '+237',  name: 'Cameroon' },
  { flag: '🇨🇦', dial: '+1',    name: 'Canada' },
  { flag: '🇨🇫', dial: '+236',  name: 'Central African Republic' },
  { flag: '🇹🇩', dial: '+235',  name: 'Chad' },
  { flag: '🇨🇱', dial: '+56',   name: 'Chile' },
  { flag: '🇨🇳', dial: '+86',   name: 'China' },
  { flag: '🇨🇴', dial: '+57',   name: 'Colombia' },
  { flag: '🇨🇬', dial: '+242',  name: 'Congo' },
  { flag: '🇨🇷', dial: '+506',  name: 'Costa Rica' },
  { flag: '🇭🇷', dial: '+385',  name: 'Croatia' },
  { flag: '🇨🇺', dial: '+53',   name: 'Cuba' },
  { flag: '🇨🇾', dial: '+357',  name: 'Cyprus' },
  { flag: '🇨🇿', dial: '+420',  name: 'Czech Republic' },
  { flag: '🇩🇰', dial: '+45',   name: 'Denmark' },
  { flag: '🇩🇯', dial: '+253',  name: 'Djibouti' },
  { flag: '🇩🇴', dial: '+1809', name: 'Dominican Republic' },
  { flag: '🇪🇨', dial: '+593',  name: 'Ecuador' },
  { flag: '🇪🇬', dial: '+20',   name: 'Egypt' },
  { flag: '🇸🇻', dial: '+503',  name: 'El Salvador' },
  { flag: '🇪🇷', dial: '+291',  name: 'Eritrea' },
  { flag: '🇪🇪', dial: '+372',  name: 'Estonia' },
  { flag: '🇸🇿', dial: '+268',  name: 'Eswatini' },
  { flag: '🇪🇹', dial: '+251',  name: 'Ethiopia' },
  { flag: '🇫🇯', dial: '+679',  name: 'Fiji' },
  { flag: '🇫🇮', dial: '+358',  name: 'Finland' },
  { flag: '🇫🇷', dial: '+33',   name: 'France' },
  { flag: '🇬🇦', dial: '+241',  name: 'Gabon' },
  { flag: '🇬🇲', dial: '+220',  name: 'Gambia' },
  { flag: '🇬🇪', dial: '+995',  name: 'Georgia' },
  { flag: '🇩🇪', dial: '+49',   name: 'Germany' },
  { flag: '🇬🇭', dial: '+233',  name: 'Ghana' },
  { flag: '🇬🇷', dial: '+30',   name: 'Greece' },
  { flag: '🇬🇹', dial: '+502',  name: 'Guatemala' },
  { flag: '🇬🇳', dial: '+224',  name: 'Guinea' },
  { flag: '🇬🇾', dial: '+592',  name: 'Guyana' },
  { flag: '🇭🇹', dial: '+509',  name: 'Haiti' },
  { flag: '🇭🇳', dial: '+504',  name: 'Honduras' },
  { flag: '🇭🇰', dial: '+852',  name: 'Hong Kong' },
  { flag: '🇭🇺', dial: '+36',   name: 'Hungary' },
  { flag: '🇮🇸', dial: '+354',  name: 'Iceland' },
  { flag: '🇮🇳', dial: '+91',   name: 'India' },
  { flag: '🇮🇩', dial: '+62',   name: 'Indonesia' },
  { flag: '🇮🇷', dial: '+98',   name: 'Iran' },
  { flag: '🇮🇶', dial: '+964',  name: 'Iraq' },
  { flag: '🇮🇪', dial: '+353',  name: 'Ireland' },
  { flag: '🇮🇱', dial: '+972',  name: 'Israel' },
  { flag: '🇮🇹', dial: '+39',   name: 'Italy' },
  { flag: '🇯🇲', dial: '+1876', name: 'Jamaica' },
  { flag: '🇯🇵', dial: '+81',   name: 'Japan' },
  { flag: '🇯🇴', dial: '+962',  name: 'Jordan' },
  { flag: '🇰🇿', dial: '+7',    name: 'Kazakhstan' },
  { flag: '🇰🇪', dial: '+254',  name: 'Kenya' },
  { flag: '🇰🇮', dial: '+686',  name: 'Kiribati' },
  { flag: '🇰🇼', dial: '+965',  name: 'Kuwait' },
  { flag: '🇰🇬', dial: '+996',  name: 'Kyrgyzstan' },
  { flag: '🇱🇦', dial: '+856',  name: 'Laos' },
  { flag: '🇱🇻', dial: '+371',  name: 'Latvia' },
  { flag: '🇱🇧', dial: '+961',  name: 'Lebanon' },
  { flag: '🇱🇸', dial: '+266',  name: 'Lesotho' },
  { flag: '🇱🇷', dial: '+231',  name: 'Liberia' },
  { flag: '🇱🇾', dial: '+218',  name: 'Libya' },
  { flag: '🇱🇮', dial: '+423',  name: 'Liechtenstein' },
  { flag: '🇱🇹', dial: '+370',  name: 'Lithuania' },
  { flag: '🇱🇺', dial: '+352',  name: 'Luxembourg' },
  { flag: '🇲🇴', dial: '+853',  name: 'Macau' },
  { flag: '🇲🇬', dial: '+261',  name: 'Madagascar' },
  { flag: '🇲🇼', dial: '+265',  name: 'Malawi' },
  { flag: '🇲🇾', dial: '+60',   name: 'Malaysia' },
  { flag: '🇲🇻', dial: '+960',  name: 'Maldives' },
  { flag: '🇲🇱', dial: '+223',  name: 'Mali' },
  { flag: '🇲🇹', dial: '+356',  name: 'Malta' },
  { flag: '🇲🇷', dial: '+222',  name: 'Mauritania' },
  { flag: '🇲🇺', dial: '+230',  name: 'Mauritius' },
  { flag: '🇲🇽', dial: '+52',   name: 'Mexico' },
  { flag: '🇫🇲', dial: '+691',  name: 'Micronesia' },
  { flag: '🇲🇩', dial: '+373',  name: 'Moldova' },
  { flag: '🇲🇨', dial: '+377',  name: 'Monaco' },
  { flag: '🇲🇳', dial: '+976',  name: 'Mongolia' },
  { flag: '🇲🇪', dial: '+382',  name: 'Montenegro' },
  { flag: '🇲🇦', dial: '+212',  name: 'Morocco' },
  { flag: '🇲🇿', dial: '+258',  name: 'Mozambique' },
  { flag: '🇲🇲', dial: '+95',   name: 'Myanmar' },
  { flag: '🇳🇦', dial: '+264',  name: 'Namibia' },
  { flag: '🇳🇵', dial: '+977',  name: 'Nepal' },
  { flag: '🇳🇱', dial: '+31',   name: 'Netherlands' },
  { flag: '🇳🇿', dial: '+64',   name: 'New Zealand' },
  { flag: '🇳🇮', dial: '+505',  name: 'Nicaragua' },
  { flag: '🇳🇪', dial: '+227',  name: 'Niger' },
  { flag: '🇳🇬', dial: '+234',  name: 'Nigeria' },
  { flag: '🇰🇵', dial: '+850',  name: 'North Korea' },
  { flag: '🇲🇰', dial: '+389',  name: 'North Macedonia' },
  { flag: '🇳🇴', dial: '+47',   name: 'Norway' },
  { flag: '🇴🇲', dial: '+968',  name: 'Oman' },
  { flag: '🇵🇰', dial: '+92',   name: 'Pakistan' },
  { flag: '🇵🇼', dial: '+680',  name: 'Palau' },
  { flag: '🇵🇸', dial: '+970',  name: 'Palestine' },
  { flag: '🇵🇦', dial: '+507',  name: 'Panama' },
  { flag: '🇵🇬', dial: '+675',  name: 'Papua New Guinea' },
  { flag: '🇵🇾', dial: '+595',  name: 'Paraguay' },
  { flag: '🇵🇪', dial: '+51',   name: 'Peru' },
  { flag: '🇵🇱', dial: '+48',   name: 'Poland' },
  { flag: '🇵🇹', dial: '+351',  name: 'Portugal' },
  { flag: '🇶🇦', dial: '+974',  name: 'Qatar' },
  { flag: '🇷🇴', dial: '+40',   name: 'Romania' },
  { flag: '🇷🇺', dial: '+7',    name: 'Russia' },
  { flag: '🇷🇼', dial: '+250',  name: 'Rwanda' },
  { flag: '🇸🇦', dial: '+966',  name: 'Saudi Arabia' },
  { flag: '🇸🇳', dial: '+221',  name: 'Senegal' },
  { flag: '🇷🇸', dial: '+381',  name: 'Serbia' },
  { flag: '🇸🇨', dial: '+248',  name: 'Seychelles' },
  { flag: '🇸🇱', dial: '+232',  name: 'Sierra Leone' },
  { flag: '🇸🇬', dial: '+65',   name: 'Singapore' },
  { flag: '🇸🇰', dial: '+421',  name: 'Slovakia' },
  { flag: '🇸🇮', dial: '+386',  name: 'Slovenia' },
  { flag: '🇸🇧', dial: '+677',  name: 'Solomon Islands' },
  { flag: '🇸🇴', dial: '+252',  name: 'Somalia' },
  { flag: '🇿🇦', dial: '+27',   name: 'South Africa' },
  { flag: '🇸🇸', dial: '+211',  name: 'South Sudan' },
  { flag: '🇰🇷', dial: '+82',   name: 'South Korea' },
  { flag: '🇪🇸', dial: '+34',   name: 'Spain' },
  { flag: '🇱🇰', dial: '+94',   name: 'Sri Lanka' },
  { flag: '🇸🇩', dial: '+249',  name: 'Sudan' },
  { flag: '🇸🇷', dial: '+597',  name: 'Suriname' },
  { flag: '🇸🇪', dial: '+46',   name: 'Sweden' },
  { flag: '🇨🇭', dial: '+41',   name: 'Switzerland' },
  { flag: '🇸🇾', dial: '+963',  name: 'Syria' },
  { flag: '🇹🇼', dial: '+886',  name: 'Taiwan' },
  { flag: '🇹🇯', dial: '+992',  name: 'Tajikistan' },
  { flag: '🇹🇿', dial: '+255',  name: 'Tanzania' },
  { flag: '🇹🇭', dial: '+66',   name: 'Thailand' },
  { flag: '🇹🇱', dial: '+670',  name: 'Timor-Leste' },
  { flag: '🇹🇬', dial: '+228',  name: 'Togo' },
  { flag: '🇹🇴', dial: '+676',  name: 'Tonga' },
  { flag: '🇹🇹', dial: '+1868', name: 'Trinidad and Tobago' },
  { flag: '🇹🇳', dial: '+216',  name: 'Tunisia' },
  { flag: '🇹🇷', dial: '+90',   name: 'Turkey' },
  { flag: '🇹🇲', dial: '+993',  name: 'Turkmenistan' },
  { flag: '🇹🇻', dial: '+688',  name: 'Tuvalu' },
  { flag: '🇺🇬', dial: '+256',  name: 'Uganda' },
  { flag: '🇺🇦', dial: '+380',  name: 'Ukraine' },
  { flag: '🇦🇪', dial: '+971',  name: 'United Arab Emirates' },
  { flag: '🇬🇧', dial: '+44',   name: 'United Kingdom' },
  { flag: '🇺🇸', dial: '+1',    name: 'United States' },
  { flag: '🇺🇾', dial: '+598',  name: 'Uruguay' },
  { flag: '🇺🇿', dial: '+998',  name: 'Uzbekistan' },
  { flag: '🇻🇺', dial: '+678',  name: 'Vanuatu' },
  { flag: '🇻🇪', dial: '+58',   name: 'Venezuela' },
  { flag: '🇻🇳', dial: '+84',   name: 'Vietnam' },
  { flag: '🇾🇪', dial: '+967',  name: 'Yemen' },
  { flag: '🇿🇲', dial: '+260',  name: 'Zambia' },
  { flag: '🇿🇼', dial: '+263',  name: 'Zimbabwe' },
];

export const CITIZENSHIP_OPTIONS = ['Filipino', 'Others'];

export const CITIZENSHIP_LIST = [
  'Afghan', 'Albanian', 'Algerian', 'American', 'Andorran', 'Angolan',
  'Antiguan and Barbudan', 'Argentine', 'Armenian', 'Australian', 'Austrian', 'Azerbaijani',
  'Bahamian', 'Bahraini', 'Bangladeshi', 'Barbadian', 'Belarusian', 'Belgian',
  'Belizean', 'Beninese', 'Bhutanese', 'Bolivian', 'Bosnian', 'Botswanan',
  'Brazilian', 'British', 'Bruneian', 'Bulgarian', 'Burkinabé', 'Burundian',
  'Cambodian', 'Cameroonian', 'Canadian', 'Cape Verdean', 'Central African',
  'Chadian', 'Chilean', 'Chinese', 'Colombian', 'Comoran', 'Congolese',
  'Costa Rican', 'Croatian', 'Cuban', 'Cypriot', 'Czech',
  'Danish', 'Djiboutian', 'Dominican',
  'Ecuadorian', 'Egyptian', 'Emirati', 'Equatorial Guinean', 'Eritrean', 'Estonian', 'Ethiopian',
  'Fijian', 'Filipino', 'Finnish', 'French',
  'Gabonese', 'Gambian', 'Georgian', 'German', 'Ghanaian', 'Greek', 'Grenadian',
  'Guatemalan', 'Guinean', 'Guinea-Bissauan', 'Guyanese',
  'Haitian', 'Honduran', 'Hungarian',
  'Icelandic', 'Indian', 'Indonesian', 'Iranian', 'Iraqi', 'Irish', 'Israeli', 'Italian', 'Ivorian',
  'Jamaican', 'Japanese', 'Jordanian',
  'Kazakhstani', 'Kenyan', 'Kiribatian', 'Kuwaiti', 'Kyrgyzstani',
  'Laotian', 'Latvian', 'Lebanese', 'Basotho', 'Liberian', 'Libyan', 'Liechtensteiner', 'Lithuanian', 'Luxembourgish',
  'Malagasy', 'Malawian', 'Malaysian', 'Maldivian', 'Malian', 'Maltese', 'Marshallese',
  'Mauritanian', 'Mauritian', 'Mexican', 'Micronesian', 'Moldovan', 'Monegasque', 'Mongolian',
  'Montenegrin', 'Moroccan', 'Mozambican', 'Myanmarese',
  'Namibian', 'Nauruan', 'Nepali', 'New Zealander', 'Nicaraguan', 'Nigerian', 'Nigerien',
  'North Korean', 'North Macedonian', 'Norwegian',
  'Omani',
  'Pakistani', 'Palauan', 'Palestinian', 'Panamanian', 'Papua New Guinean', 'Paraguayan', 'Peruvian',
  'Polish', 'Portuguese',
  'Qatari',
  'Romanian', 'Russian', 'Rwandan',
  'Saint Lucian', 'Samoan', 'Sao Tomean', 'Saudi', 'Senegalese', 'Serbian', 'Seychellois',
  'Sierra Leonean', 'Singaporean', 'Slovak', 'Slovenian', 'Solomon Islander', 'Somali',
  'South African', 'South Korean', 'South Sudanese', 'Spanish', 'Sri Lankan', 'Sudanese',
  'Surinamese', 'Swedish', 'Swiss', 'Syrian',
  'Taiwanese', 'Tajik', 'Tanzanian', 'Thai', 'Timorese', 'Togolese', 'Tongan',
  'Trinidadian', 'Tunisian', 'Turkish', 'Turkmen', 'Tuvaluan',
  'Ugandan', 'Ukrainian', 'Uruguayan', 'Uzbekistani',
  'Vanuatuan', 'Venezuelan', 'Vietnamese',
  'Yemeni',
  'Zambian', 'Zimbabwean',
];

export const REASON_OPTIONS = [
  'Gift', 'Relocation', 'Primary Home', 'Investment',
  'Secondary / Vacation / Retirement Home', 'Upgrade',
];

export const SOURCE_OPTIONS = [
  'Sales Boosting', 'Company Initiated Activities', 'Online Ads / Website',
  'Showroom Walk-in', 'Personal', 'Referral', 'Repeat Buyer',
];

export const INCOME_OPTIONS = [
  'Php 50,000 to Php 100,000',
  'Php 100,001 to Php 150,000',
  'Above Php 150,000',
];
